name: "Build iOS app"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs:
  build_and_test:
    runs-on: macos-15
    defaults:
      run:
        working-directory: RFR
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: build archive
        run: |
          xcodebuild -project RFR.xcodeproj -scheme RFR -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=latest' clean test -testPlan RFR-CI
